version: '3.1'
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 8885:3306
#    volumes:
#          - ./docker-data/db-data:/var/lib/mysql #where the database will get saved and loaded it doesnt work on windows home
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_SCHEMA}

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080